version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s-kun-app
    depends_on:
      - rabbitmq
    command: bun run src/index.ts
    ports:
      - "3023:3023"
    env_file:
      - .env
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: s-kun-worker
    command: bun run ./mc-workers.ts
    env_file:
      - .env
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: kun-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
